default:
  namenode_heap: 512m
  namenode_young_heap: 128m
  datanode_heap: 512m
  datanode_young_heap: 128m
  journalnode_heap: 256m
  journalnode_young_heap: 64m
  zkfc_heap: 256m
  zkfc_young_heap: 64m

  hadoop_release_tarball: hadoop-2.7.3.2.6.5.0-SNAPSHOT.tar.gz
  hadoop_release_version: hadoop-2.7.3.2.6.5.0-SNAPSHOT