default:
  namenode_heap: 512m
  namenode_young_heap: 128m
  datanode_heap: 512m
  datanode_young_heap: 128m
  journalnode_heap: 256m
  journalnode_young_heap: 64m
  zkfc_heap: 256m
  zkfc_young_heap: 64m
  jobhistoryserver_heap: 512m
  jobhistoryserver_young_heap: 64m

  namenode1: ip-172-31-41-170.us-west-2.compute.internal
  namenode2: ip-172-31-47-83.us-west-2.compute.internal

  dfs_namenode_name_dir: /data/hdfs/namenode
  dfs_journalnode_edits_dir: /data/hdfs/journalnode

  hadoop_release_tarball: hadoop-2.7.3.2.6.5.0-SNAPSHOT.tar.gz
  hadoop_release_version: hadoop-2.7.3.2.6.5.0-SNAPSHOT

slave:
  dfs_datanode_data_dir: /data/hdfs/datanode