namenode_heap: 4096m
namenode_young_heap: 512m
resourcemanager_heap: 2048m
resourcemanager_young_heap: 512m
datanode_heap: 2048m
datanode_young_heap: 256m
nodemanager_heap: 2048m
nodemanager_young_heap: 256m
journalnode_heap: 1024m
journalnode_young_heap: 128m
zkfc_heap: 512m
zkfc_young_heap: 128m
jobhistoryserver_heap: 2048m
jobhistoryserver_young_heap: 256m

namenode_http_port: 50070
namenode_client_rpc_port: 8020
namenode_service_rpc_port: 8030
namenode_lifeline_rpc_port: 8040

journalnode_rpc_port: 8485
journalnoed_http_port: 8480

datanode_ipc_port: 50020
datanode_http_port: 50075
datanode_port: 50010

resourcemanager_port: 8032
resourcemanager_scheduler_port: 8034
resourcemanager_webapp_port: 50030
resourcemanager_resource_tracker_port: 8031
resourcemanager_admin_port: 8033

nodemanager_webapp_port: 50060
nodemanager_port: 45454
nodemanager_localizer_port: 45455

jobhistoryserver_port: 10020
jobhistoryserver_webapp_port: 19888
jobhistoryserver_admin_port: 10033

hadoop_release_tarball: hadoop-2.7.3.2.6.5.0-SNAPSHOT.tar.gz
hadoop_release_version: hadoop-2.7.3.2.6.5.0-SNAPSHOT
