hadoop.tmp.dir: /tmp/hadoop-${user.name}
net.topology.script.file.name: "{% hadoop_confs_dir %}/hadoop/conf/topology.py"
hadoop.security.authentication: simple
fs.trash.interval: 1440
fs.defaultFS: hdfs://{% default_nameservice %}
ha.zookeeper.parent-znode: /hadoop-ha
ha.zookeeper.quorum: "{%zookeeper_quorum%}"
hadoop.proxyuser.mapred.groups: "*"
hadoop.proxyuser.mapred.hosts: "*"