inventory:
    ip-172-31-38-97.us-west-2.compute.internal:
        roles:
          - resourcemanager
          - nodemanager
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal
    ip-172-31-32-63.us-west-2.compute.internal:
        roles:
          - nodemanager
          - spark_cli
          - hadoop_cli
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal