inventory:
    smao-dev-5-1999788.slc07.dev.ebayc3.com:
        roles:
          - resourcemanager
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal
    smao-dev-6-1999789.slc07.dev.ebayc3.com:
        roles:
          - nodemanager
          - spark_cli
          - hadoop_cli
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal