zookeeper_port: 2181
zookeeper_data_dir: /tmp/hadoop-zookeeper

zookeeper_release_tarball: "{% required %}"
zookeeper_release_version: "{% required %}"

zookeeper_heap: 2048m
zookeeper_young_heap: 256m