install_base_dir: /apache
kerberos: false

hadoop_log_dir: /var/log/hadoop
hadoop_pid_dir: /var/run/hadoop_pids

namenode_heap: 4g
namenode_young_heap: 512m
resource_manager_heap: 2g
resource_manager_young_heap: 512m
datanode_heap: 2g
nodemanager_heap: 2g

namenode_http_port: 50070
namenode_client_rpc_port: 8020
namenode_service_rpc_port: 8030
namenode_lifeline_rpc_port: 8040

journalnode_rpc_port: 8485
journalnoed_http_port: 8480

datanode_ipc_port: 50020
datanode_http_port: 50075
datanode_port: 50010

resource_manager_port: 8032
resource_manager_scheduler_port: 8030
resource_manager_webapp_port: 50030
resource_manager_resource_tracker_port: 8031
resource_manager_admin_port: 8033

nodemanager_webapp_port: 50060
nodemanager_port: 0
nodemanager_localizer_port: 8040

hadoop_release_tarball: hadoop-2.7.3.2.6.5.0-SNAPSHOT.tar.gz
hadoop_release_version: hadoop-2.7.3.2.6.5.0-SNAPSHOT
