- name: create {{ install_base_dir }}
  file: path={{ item }} state=directory mode=0755 owner=root group=root
  with_items:
    - "{{ install_base_dir }}"
    - "{{ install_base_dir }}/releases"
    - "{{ install_base_dir }}/confs"