- name: create {{ install_base_dir }}
  file: path={{ item }} state=directory mode=0755 owner=root group=root
  with_items:
    - "{{ install_base_dir }}"
    - "{{ install_base_dir }}/releases"
    - "{{ install_base_dir }}/confs"
    - "{{ install_base_dir }}/run"

- name: create hadoop pid dir
  file: path={{ item }} state=directory mode=0775 owner=root group=hadoop
  with_items:
    - "{{ install_base_dir }}/run/pids"

- name: create hadoop log dir
  file: path={{ item }} state=directory mode=0775 owner=root group=hadoop
  with_items:
    - "{{hadoop_log_dir}}"
  ignore_errors: yes