- name: install zookeeper.service
  template: src=files/zookeeper.service.j2 dest=/usr/lib/systemd/system/zookeeper.service group=root owner=root mode=0644
  when: '"zookeeper" in group_names'

- name: install datanode.service
  template: src="files/datanode.service.j2" dest=/usr/lib/systemd/system/datanode.service group=root owner=root mode=0644
  when: '"datanode" in group_names'

- name: install namenode.service
  template: src="files/namenode.service.j2" dest=/usr/lib/systemd/system/namenode.service group=root owner=root mode=0644
  when: '"namenode" in group_names'

- name: install zkfc.service
  template: src="files/zkfc.service.j2" dest=/usr/lib/systemd/system/zkfc.service group=root owner=root mode=0644
  when: '"namenode" in group_names'

- name: install journalnode.service
  template: src="files/journalnode.service.j2" dest=/usr/lib/systemd/system/journalnode.service group=root owner=root mode=0644
  when: '"journalnode" in group_names'

- name: install nodemanager.service
  template: src="files/nodemanager.service.j2" dest=/usr/lib/systemd/system/nodemanager.service group=root owner=root mode=0644
  when: '"nodemanager" in group_names'

- name: install resourcemanager.service
  template: src="files/resourcemanager.service.j2" dest=/usr/lib/systemd/system/resourcemanager.service group=root owner=root mode=0644
  when: '"resourcemanager" in group_names'

- name: install sparkhistoryserver.service
  template: src="files/sparkhistoryserver.service.j2" dest=/usr/lib/systemd/system/sparkhistoryserver.service group=root owner=root mode=0644
  when: '"sparkhistoryserver" in group_names'

- name: reload services
  command: systemctl daemon-reload

- name: enable zookeeper service
  command: systemctl enable zookeeper
  when: '"zookeeper" in group_names'

- name: enable datanode service
  command: systemctl enable datanode
  when: '"datanode" in group_names'

- name: enable namenode & zkfc service
  command: systemctl enable namenode zkfc
  when: '"namenode" in group_names'

- name: enable journalnode service
  command: systemctl enable journalnode
  when: '"journalnode" in group_names'

- name: enable nodemanager service
  command: systemctl enable nodemanager
  when: '"nodemanager" in group_names'

- name: enable resourcemanager service
  command: systemctl enable resourcemanager
  when: '"resourcemanager" in group_names'

- name: enable sparkhistoryserver service
  command: systemctl enable sparkhistoryserver
  when: '"sparkhistoryserver" in group_names'
