- name: install {{ service_name }}.service
  template: src=files/{{ service_name }}.service.j2 dest=/usr/lib/systemd/system/{{ service_name }}.service group=root owner=root mode=0644
  when: 'service_name in group_names'

- name: reload services
  command: systemctl daemon-reload
  when: 'service_name in group_names'

- name: enable {{ service_name }} service
  command: systemctl enable {{ service_name }}
  when: 'service_name in group_names'
