- name: Install spark for config group {{ config_group_name }}
  hosts: "{{ variable_hosts | default('all') }}"
  tasks:
    - name: load vars
      include_vars: file="{{ vars_file | default('vars/default.yaml') }}"

    - name: before install preparation
      include: before_install_service.yaml

    - name: sync spark release
      unarchive: src=../releases/{{ spark_release_tarball }} dest={{ install_base_dir }}/releases owner=root group=root mode=0755
      when: (sync_release is not defined) or (sync_release is defined and sync_release|bool)

    - name: create spark soft link
      file: src=releases/{{ spark_release_version }} path={{ install_base_dir }}/spark state=link


    - name: create spark confs dir
      file: path={{ item }} state=directory mode=0755 owner=root group=hadoop
      with_items:
        - "{{ install_base_dir }}/confs/spark/conf"

    - name: sync spark confs
      copy: src={{ group_conf_dir }}/{{ item }} dest={{ install_base_dir }}/confs/spark/conf/{{ item }} mode=0644 owner=root group=hadoop
      with_items:
        - log4j.properties
        - spark-defaults.conf
        - spark-env.sh

    - name: delete original  spark_dir/conf
      file: path={{ install_base_dir }}/spark/conf state=absent

    - name: create hadoop conf soft link
      file: src={{ install_base_dir }}/confs/spark/conf path={{ install_base_dir }}/spark/conf state=link

    - name: install systemd service
      include: install_systemd_service.yml

