- name: Install java for config group {{ config_group_name }}
  hosts: "{{ variable_hosts | default('all') }}"
  tasks:
    - name: load vars
      include_vars: file="{{ vars_file | default('vars/default.yaml') }}"

    - name: delete java release
      file: path={{ hadoop_releases_dir }}/{{ java_release_version }} state=absent

    - name: sync java release
      unarchive: src=../releases/{{ java_release_tarball }} dest={{ hadoop_releases_dir }} owner=root group=root mode=0755

    - name: java soft link
      file: src={{ hadoop_releases_dir }}/{{ java_release_version }} path={{ install_base_dir }}/java state=link
