- name: Install java
  hosts: "{{ variable_hosts | default('all') }}"

  tasks:
    - name: load vars
      include_vars: file="{{vars_file}} | default('vars/default.yaml')"
      
    - name: prepare node
      include: prepare_node.yaml

    - name: sync java release
      unarchive: src=releases/{{ java_release_tarball }} dest={{ install_base_dir }}/releases owner=root group=root mode=0755

    - name: java soft link
      file: src=releases/{{ java_release_version }} path={{ install_base_dir }}/java state=link
