- name: Install zookeeper for config group {{ config_group_name }}
  hosts: "{{ variable_hosts | default('all') }}"
  tasks:
    - name: load vars
      include_vars: file="{{ vars_file | default('vars/default.yaml') }}"

    - name: before install preparation
      include: include/before_install_service.yaml service_user=zookeeper

    - name: sync zookeeper release
      unarchive: src=../releases/{{ zookeeper_release_tarball }} dest={{ hadoop_releases_dir }} owner=root group=hadoop
      when: (sync_release is not defined) or (sync_release is defined and sync_release|bool)

    - name: create zookeeper soft link
      file: src=releases/{{ zookeeper_release_version }} path={{ install_base_dir }}/zookeeper state=link


    - name: create zookeeper confs dir
      file: path={{ item }} state=directory mode=0755 owner=root group=hadoop
      with_items:
        - "{{ hadoop_confs_dir }}/zookeeper/conf"

    - name: sync zookeeper confs
      copy: src={{ group_conf_dir }}/{{ item }} dest={{ hadoop_confs_dir }}/zookeeper/conf/{{ item }} mode=0644 owner=root group=hadoop
      with_items:
        - zoo.cfg
        - zookeeper-env.sh
        - log4j.properties

    - name: delete original zookeeper_dir/conf
      file: path={{ install_base_dir }}/zookeeper/conf state=absent

    - name: create zookeeper conf soft link
      file: src={{ hadoop_confs_dir }}/zookeeper/conf path={{ install_base_dir }}/zookeeper/conf state=link


    - name: create zookeeper storage dir
      file: path={{ item }} state=directory mode=0755 owner=zookeeper group=hadoop
      with_items:
        - "{{zookeeper_storage_dir}}"
      when: '"zookeeper" in group_names'

    - name: create zookeeper myid file
      copy: content="{{ hostvars[inventory_hostname]['host_params'][inventory_hostname]['zookeeper_myid'] }}" mode=0644 owner=zookeeper group=hadoop dest={{zookeeper_storage_dir}}/myid
      when: '"zookeeper" in group_names'

    - name: install systemd service
      include: include/install_systemd_service.yml service_name={{ item }}
      with_items:
        - zookeeper