- name: Prepare node
  hosts: "{{ variable_hosts | default('all') }}"
  gather_facts: no
  tasks:
    - name: add hadoop group
      group: name=hadoop

    - name: add hadoop users
      user: name={{ item.name }} groups=hadoop append=yes
      with_items:
        - {name: "zookeeper"}
        - {name: "hdfs"}
        - {name: "yarn"}
        - {name: "hbase"}
        - {name: "spark"}
        - {name: "hive"}

    - name: set ulimit
      copy: src=files/limits.conf dest=/etc/security/limits.conf mode=0644 owner=root group=root

    - name: create base installtion directory
      file: path={{ item }} state=directory mode=0755 owner=root group=root
      with_items:
        - "{{ install_base_dir }}"
        - "{{ hadoop_releases_dir }}"
        - "{{ hadoop_confs_dir }}"
        - "{{ hadoop_run_dir }}"

    - name: create hadoop pid dir
      file: path={{ item }} state=directory mode=0775 owner=root group=hadoop
      with_items:
        - "{{ hadoop_pid_dir }}"

    - name: create hadoop log dir
      file: path={{ item }} state=directory mode=0775 owner=root group=hadoop
      with_items:
        - "{{hadoop_log_dir}}"
      ignore_errors: yes