- name: Start Resource Manager Service
  hosts: resourcemanager
  gather_facts: no
  tasks:
    - name: start Resource Manager service
      import_tasks: include/start_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - resourcemanager

- name: Start Node Manager Service
  hosts: nodemanager
  gather_facts: no
  tasks:
    - name: start Node Manager service
      import_tasks: include/start_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - nodemanager