- name: Start Resource Manager Service
  hosts: resourcemanager
  tasks:
    - name: start Resource Manager service
      include: include/start_service.yml service_name={{ item }}
      with_items:
        - resourcemanager

- name: Start Node Manager Service
  hosts: nodemanager
  tasks:
    - name: start Node Manager service
      include: include/start_service.yml service_name={{ item }}
      with_items:
        - nodemanager