- name: Start Zookeeper Service
  hosts: zookeeper
  gather_facts: no
  tasks:
    - name: start Zookeeper service
      import_tasks:

      import_tasks/start_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - zookeeper
