- name: Start Job History Server Service
  hosts: jobhistoryserver
  gather_facts: no
  tasks:
    - include_tasks: include/start_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - jobhistoryserver
