- name: Start Zookeeper Service
  hosts: zookeeper
  gather_facts: no
  tasks:
    - name: start Zookeeper service
      include_tasks: include/start_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - zookeeper
