- name: Starts Spark History Server Service
  hosts: sparkhistoryserver
  gather_facts: no
  tasks:
    - name: start Spark History Server service
      import_tasks: include/start_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - sparkhistoryserver