- name: Start Namenode Service
  hosts: namenode
  gather_facts: no
  tasks:
    - name: start namenode service
      include: include/start_service.yml service_name={{ item }}
      with_items:
        - namenode
        - zkfc

- name: Start Journal Node Service
  hosts: journalnode
  gather_facts: no
  tasks:
    - name: start journalnode service
      include: include/start_service.yml service_name={{ item }}
      with_items:
        - journalnode

- name: Start Data Node Service
  hosts: datanode
  gather_facts: no
  tasks:
    - name: start datanode service
      include: include/start_service.yml service_name={{ item }}
      with_items:
        - datanode