- name: Stop Spark History Server Service
  hosts: sparkhistoryserver
  tasks:
    - name: stop Spark History Server service
      include: include/stop_service.yml service_name={{ item }}
      with_items:
        - sparkhistoryserver