- name: Stop Spark History Server Service
  hosts: sparkhistoryserver
  gather_facts: no
  tasks:
    - name: stop Spark History Server service
      include_tasks: include/stop_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - sparkhistoryserver