- name: Stop Resource Manager Service
  hosts: resourcemanager
  gather_facts: no
  tasks:
    - name: stop Resource Manager service
      import_tasks: include/stop_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - resourcemanager

- name: Stop Node Manager Service
  hosts: nodemanager
  gather_facts: no
  tasks:
    - name: stop Node Manager service
      import_tasks: include/stop_service.yml
      vars:
        service_name: "{{ item }}"
      with_items:
        - nodemanager