- name: Stop Spark Service
  hosts: "{{ variable_hosts | default('all') }}"
  tasks:
    - name: stop Spark service
      include: include/stop_service.yml service_name={{ item }}
      with_items:
        - sparkhistoryserver