- name: Stop Namenode Service
  hosts: namenode
  gather_facts: no
  tasks:
    - name: stop namenode service
      include: include/stop_service.yml service_name={{ item }}
      with_items:
        - namenode
        - zkfc

- name: Stop Journal Node Service
  hosts: journalnode
  gather_facts: no
  tasks:
    - name: stop journalnode service
      include: include/stop_service.yml service_name={{ item }}
      with_items:
        - journalnode

- name: Stop Data Node Service
  hosts: datanode
  gather_facts: no
  tasks:
    - name: stop datanode service
      include: include/stop_service.yml service_name={{ item }}
      with_items:
        - datanode