inventory:
    ip-172-31-41-170.us-west-2.compute.internal:
        roles:
          - namenode
          - zkfc
          - journalnode
          - hivemetastore
          - zookeeper
          - jobhistoryserver
        topology: /slc/smao_dev
        vars:
          zookeeper_myid: 1
    ip-172-31-47-83.us-west-2.compute.internal:
        roles:
          - namenode
          - zkfc
          - journalnode
          - hivemetastore
          - zookeeper
          - sparkhistoryserver
        vars:
          zookeeper_myid: 2
        topology: /slc/smao_dev
    ip-172-31-46-89.us-west-2.compute.internal:
        roles:
          - journalnode
          - zookeeper
          - datanode
        topology: /slc/smao_dev
        vars:
          zookeeper_myid: 3
        config_groups:
          hadoop: normal
    ip-172-31-44-127.us-west-2.compute.internal:
        roles:
          - datanode
          - hadoop_cli
          - zookeeper_cli
          - hive_cli
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal