inventory:
    smao-dev-1-1999775.slc07.dev.ebayc3.com:
        roles:
          - namenode
          - zkfc
          - journalnode
          - resource_manager
          - hbase_master
          - hive_metastore
          - zookeeper_server
        topology: /slc/smao_dev
        vars:
          zookeeper_myid: 1
    smao-dev-2-1999780.slc07.dev.ebayc3.com:
        roles:
          - namenode
          - zkfc
          - journalnode
          - resource_manager
          - hbase_master
          - hive_metastore
          - zookeeper_server
          - spark_history_server
        vars:
          zookeeper_myid: 2
        topology: /slc/smao_dev
    smao-dev-3-1999786.slc07.dev.ebayc3.com:
        roles:
          - journalnode
          - zookeeper_server
          - datanode
          - nodemanager
          - regionserver
        topology: /slc/smao_dev
        vars:
          zookeeper_myid: 3
        config_groups:
          hadoop: normal
    smao-dev-4-1999787.slc07.dev.ebayc3.com:
        roles:
          - datanode
          - nodemanager
          - regionserver
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal
    smao-dev-5-1999788.slc07.dev.ebayc3.com:
        roles:
          - datanode
          - nodemanager
          - regionserver
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal
    smao-dev-6-1999789.slc07.dev.ebayc3.com:
        roles:
          - datanode
          - nodemanager
          - regionserver
          - spark_cli
          - hbase_cli
          - hadoop_cli
          - zookeeper_cli
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal