inventory:
    smao-dev-1-1999775.slc07.dev.ebayc3.com:
        roles:
          - namenode
          - zkfc
          - journalnode
          - hivemetastore
          - zookeeper
        topology: /slc/smao_dev
        vars:
          zookeeper_myid: 1
    smao-dev-2-2090152.slc07.dev.ebayc3.com:
        roles:
          - namenode
          - zkfc
          - journalnode
          - hivemetastore
          - zookeeper
          - sparkhistoryserver
        vars:
          zookeeper_myid: 2
        topology: /slc/smao_dev
    smao-dev-3-1999786.slc07.dev.ebayc3.com:
        roles:
          - journalnode
          - zookeeper
          - datanode
        topology: /slc/smao_dev
        vars:
          zookeeper_myid: 3
        config_groups:
          hadoop: normal
    smao-dev-4-1999787.slc07.dev.ebayc3.com:
        roles:
          - datanode
          - hadoop_cli
          - zookeeper_cli
        topology: /slc/smao_dev
        config_groups:
          hadoop: normal