default:
    yarn.nodemanager.resource.memory-mb: 2048
    yarn.resourcemanager.bind-host: 0.0.0.0
normal:
    yarn.nodemanager.log-dirs: /data/yarn/nodemanager/log
    yarn.nodemanager.local-dirs: /data/yarn/nodemanager/local
